script return log when error occours

diff --git a/lib/lib_run_scripts_in_folder b/lib/lib_run_scripts_in_folder
--- a/lib/lib_run_scripts_in_folder
+++ b/lib/lib_run_scripts_in_folder
@@ -29,7 +29,7 @@ find "$SCRIPT_FOLDER" -type f -name "*.sh" -print0 | while IFS= read -r -d '' sc
     if [ -x "$script" ]; then
         script_name=$(basename "$script")
         echo -e "$IGNITION_TASK Executing: $script_name"
-        bash "$script"
+        bash "$script" || echo -e "$IGNITION_FAIL Error executing: $script_name"
     fi
 done
 
